#ifndef GLOBALS_H_
#define GLOBALS_H_

int NUM_VALUES_ON_TABLE = 3;
int TABLE_VALUES_HIGH = 4;
int TABLE_VALUES_LOW = 1;

int NUM_CARDS_IN_HAND = 5;
int CARD_VALUES_HIGH = 10;
int CARD_VALUES_LOW = 5;

int ACTION_POINTS_AVALIBLE = 4;

#endif GLOBALS_H_
